apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 3  #
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app-container
        image: autoscaling:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"   # Set memory request
            cpu: "100m"       # Set CPU request
          limits:
            memory: "512Mi"   # Set memory limit
            cpu: "250m"       # Set CPU limit
